import clsx from "clsx";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "min-h-screen flex flex-col")}>
        <header className="h-16 flex items-center bg-slate-600 w-full p-6">
          <h1>
            <Link href="/">Dor Shinar</Link>
          </h1>
        </header>
        <main className="flex grow flex-col items-center">{children}</main>
        <footer className="">
          © {new Date().getFullYear()} Dor Shinar, built with{" "}
          <Link href="https://nextjs.org/">Next.js</Link>
        </footer>
      </body>
    </html>
  );
}
